const STORAGE_KEY='rg-reporting-demo:v1';

const defaults=[{
 id:'demo-harbor',slug:'harbor-residences',title:'Harbor Residences',clientName:'Nordlicht Immobilien',propertyName:'Harbor Residences',location:'Hamburg HafenCity',startDate:'2026-05-04',endDate:'2026-06-14',spend:8640,leads:113,impressions:284700,clicks:4938,seed:42817,campaigns:'Lead Ads | 52\nRetargeting | 28\nVideo Views | 20'
},{
 id:'demo-park',slug:'park-villen',title:'Park Villen',clientName:'Hanseatic Living',propertyName:'Park Villen',location:'Hamburg Alsterdorf',startDate:'2026-03-09',endDate:'2026-04-26',spend:12480,leads:157,impressions:418200,clicks:7416,seed:9134,campaigns:'Neubau Leads | 60\nInstagram Reels | 24\nRetargeting | 16'
}];
function loadCases(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(x)&&x.length)return x}catch{}saveCases(defaults);return structuredClone(defaults)}
function saveCases(cases){localStorage.setItem(STORAGE_KEY,JSON.stringify(cases))}
function euro(v,d=0){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',minimumFractionDigits:d,maximumFractionDigits:d}).format(v)}
function integer(v){return new Intl.NumberFormat('de-DE').format(Math.round(v))}
function dateLabel(v){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v+'T12:00:00'))}
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function dateRange(start,end){const out=[];let d=new Date(start+'T12:00:00'),last=new Date(end+'T12:00:00');while(d<=last&&out.length<370){out.push(new Date(d));d.setDate(d.getDate()+1)}return out}
function distribute(total,weights){const sum=weights.reduce((a,b)=>a+b,0)||1;const raw=weights.map(x=>x/sum*total);const base=raw.map(Math.floor);let rest=total-base.reduce((a,b)=>a+b,0);raw.map((x,i)=>({i,r:x-base[i]})).sort((a,b)=>b.r-a.r).slice(0,rest).forEach(x=>base[x.i]++);return base}
function parseCampaigns(text){const rows=(text||'Lead Ads | 60\nRetargeting | 25\nVideo Views | 15').split('\n').map(x=>x.trim()).filter(Boolean).map((row,i)=>{const [name,w]=row.split('|').map(x=>x.trim());return{name:name||`Kampagne ${i+1}`,weight:Number(w)||0}});if(!rows.some(x=>x.weight>0))rows.forEach((x,i)=>x.weight=Math.max(10,100-i*18));return rows}
function generate(c){const dates=dateRange(c.startDate,c.endDate),rnd=mulberry32(Number(c.seed)||1);const weights=dates.map((d,i)=>{const weekday=d.getDay(),weekend=weekday===0||weekday===6;const ramp=Math.min(1,(i+2)/6);const optimization=.88+.22*(i/Math.max(1,dates.length-1));const pulse=.72+rnd()*.62;return pulse*ramp*optimization*(weekend?.82:1.05)});const leadWeights=weights.map((w,i)=>w*(.78+rnd()*.48)*(i>dates.length*.55?1.08:1));const spendCents=distribute(Math.round(Number(c.spend)*100),weights);const leads=distribute(Number(c.leads),leadWeights);const impressions=distribute(Number(c.impressions),weights.map(w=>w*(.9+rnd()*.2)));const clicks=distribute(Number(c.clicks),weights.map((w,i)=>w*(.82+rnd()*.35)*(leads[i]?1.03:1)));const daily=dates.map((date,i)=>({date,spend:spendCents[i]/100,leads:leads[i],impressions:impressions[i],clicks:clicks[i]}));const defs=parseCampaigns(c.campaigns),cw=defs.map(x=>x.weight);const cs=distribute(Math.round(Number(c.spend)*100),cw),cl=distribute(Number(c.leads),cw.map((w,i)=>w*(1.12-i*.07))),ci=distribute(Number(c.impressions),cw),cc=distribute(Number(c.clicks),cw.map((w,i)=>w*(1.06-i*.04)));const campaigns=defs.map((x,i)=>({name:x.name,spend:cs[i]/100,leads:cl[i],impressions:ci[i],clicks:cc[i],cpl:cl[i]?cs[i]/100/cl[i]:0}));return{daily,campaigns}}
function toast(msg){const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function setDefaultDates(form){const end=new Date(),start=new Date();start.setDate(end.getDate()-41);const iso=d=>d.toISOString().slice(0,10);form.startDate.value=iso(start);form.endDate.value=iso(end)}
function fillForm(form,c){for(const [k,v] of Object.entries(c||{}))if(form.elements[k])form.elements[k].value=v??'';form.dataset.id=c?.id||''}
function formCase(form){const o=Object.fromEntries(new FormData(form));for(const k of ['spend'])o[k]=Number(o[k]);for(const k of ['leads','impressions','clicks','seed'])o[k]=Math.round(Number(o[k]));o.id=form.dataset.id||((crypto.randomUUID&&crypto.randomUUID())||`case-${Date.now()}`);return o}
function initEditor(){let cases=loadCases(),active=cases[0]?.id||null;const form=document.querySelector('#caseForm'),list=document.querySelector('#caseList'),del=document.querySelector('#deleteCase');function render(){list.innerHTML=cases.map(c=>`<div class="case-row ${c.id===active?'active':''}" data-id="${c.id}"><b>${escapeHtml(c.title)}</b><span>${escapeHtml(c.location)} · ${integer(c.leads)} Leads</span></div>`).join('')||'<div class="case-row"><span>Noch keine Cases</span></div>';list.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>{active=el.dataset.id;fillForm(form,cases.find(c=>c.id===active));render()});del.style.visibility=active?'visible':'hidden'}fillForm(form,cases[0]);render();form.onsubmit=e=>{e.preventDefault();const c=formCase(form);const idx=cases.findIndex(x=>x.id===c.id);if(idx>=0)cases[idx]=c;else cases.unshift(c);active=c.id;saveCases(cases);render();toast('Demo-Case gespeichert');setTimeout(()=>location.href=`index.html?case=${encodeURIComponent(c.slug)}`,300)};document.querySelector('#newCase').onclick=()=>{active=null;form.reset();form.dataset.id='';setDefaultDates(form);form.seed.value=Math.floor(Math.random()*90000)+10000;form.spend.value=8000;form.leads.value=100;form.impressions.value=250000;form.clicks.value=4200;form.campaigns.value='Lead Ads | 55\nRetargeting | 25\nVideo Views | 20';render()};document.querySelector('#randomize').onclick=()=>{form.seed.value=Math.floor(Math.random()*900000)+1;toast('Neue Verlaufskurve erzeugt')};del.onclick=()=>{if(!active||!confirm('Diesen Demo-Case löschen?'))return;cases=cases.filter(x=>x.id!==active);active=cases[0]?.id||null;saveCases(cases);if(active)fillForm(form,cases[0]);else document.querySelector('#newCase').click();render()};document.querySelector('#exportCases').onclick=()=>{const blob=new Blob([JSON.stringify(cases,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rg-reporting-demo-cases.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('#importCases').onchange=async e=>{try{const incoming=JSON.parse(await e.target.files[0].text());if(!Array.isArray(incoming))throw 0;cases=incoming;active=cases[0]?.id||null;saveCases(cases);if(active)fillForm(form,cases[0]);render();toast('Cases importiert')}catch{toast('Ungültige JSON-Datei')}}}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
let chart;
function renderViewer(c){const generated=generate(c),set=(id,val)=>document.querySelector(id).textContent=val;set('#caseTitle',c.title);set('#caseMeta',`${c.clientName} · ${c.location}`);set('#spend',euro(c.spend));set('#period',`${dateLabel(c.startDate)} – ${dateLabel(c.endDate)}`);set('#leads',integer(c.leads));set('#cpl',euro(c.spend/c.leads,2));set('#impressions',integer(c.impressions));set('#clicks',integer(c.clicks));set('#ctr',`${(c.clicks/c.impressions*100).toFixed(2).replace('.',',')} %`);set('#propertyName',c.propertyName);set('#propertyLocation',c.location);set('#propertyPeriod',`${dateLabel(c.startDate)} – ${dateLabel(c.endDate)}`);document.querySelector('#campaignList').innerHTML=generated.campaigns.map(x=>`<div class="campaign-item"><div><div class="campaign-name">${escapeHtml(x.name)}</div><div class="campaign-meta">Campaign Flight</div></div><div class="metric"><b>${integer(x.leads)}</b><span>Leads</span></div><div class="metric"><b>${euro(x.spend)}</b><span>Spend</span></div><div class="metric"><b>${euro(x.cpl,2)}</b><span>CPL</span></div></div>`).join('');if(chart)chart.destroy();const labels=generated.daily.map(x=>new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit'}).format(x.date));chart=new Chart(document.querySelector('#performanceChart'),{type:'line',data:{labels,datasets:[{label:'Leads',data:generated.daily.map(x=>x.leads),borderColor:'#e7352e',backgroundColor:'rgba(231,53,46,.12)',fill:true,tension:.38,pointRadius:1.5,yAxisID:'y'},{label:'Spend',data:generated.daily.map(x=>x.spend),borderColor:'#2c3245',backgroundColor:'transparent',tension:.38,pointRadius:0,yAxisID:'y1'}]},options:{animation:false,responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{backgroundColor:'rgba(26,26,46,.94)',padding:12,cornerRadius:10}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:9,color:'#9297a5'}},y:{beginAtZero:true,grid:{color:'rgba(0,0,0,.045)'},ticks:{precision:0,color:'#9297a5'}},y1:{beginAtZero:true,position:'right',grid:{display:false},ticks:{color:'#9297a5',callback:v=>`${v} €`}}}}})}
function initViewer(){const cases=loadCases(),select=document.querySelector('#caseSelect'),wanted=new URLSearchParams(location.search).get('case'),current=cases.find(x=>x.slug===wanted)||cases[0];select.innerHTML=cases.map(c=>`<option value="${escapeHtml(c.slug)}">${escapeHtml(c.title)}</option>`).join('');select.value=current.slug;select.onchange=()=>{history.replaceState(null,'',`?case=${encodeURIComponent(select.value)}`);renderViewer(cases.find(x=>x.slug===select.value))};renderViewer(current)}
if(document.body.dataset.page==='editor')initEditor();else initViewer();
